//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDPQuestions
    {
        public CDPQuestions()
        {
            this.CDPQuestionTables = new HashSet<CDPQuestionTables>();
            this.CDPQuestionValidations = new HashSet<CDPQuestionValidations>();
            this.CDPTableColumns = new HashSet<CDPTableColumns>();
        }
    
        public System.Guid QId { get; set; }
        public string QuestionId { get; set; }
        public string Title { get; set; }
        public string QuestionText { get; set; }
        public System.Guid QuestionType { get; set; }
        public int QuestionOrder { get; set; }
        public System.Guid QuestionGroupId { get; set; }
        public Nullable<System.Guid> ParentQuestionId { get; set; }
        public bool IsQuestionSubItem { get; set; }
        public bool EligibleForPrePopulation { get; set; }
        public Nullable<bool> IsApplicable { get; set; }
    
        public virtual CDPQuestionType CDPQuestionType { get; set; }
        public virtual ICollection<CDPQuestionTables> CDPQuestionTables { get; set; }
        public virtual ICollection<CDPQuestionValidations> CDPQuestionValidations { get; set; }
        public virtual ICollection<CDPTableColumns> CDPTableColumns { get; set; }
    }
}
