//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDPQuestionType
    {
        public CDPQuestionType()
        {
            this.CDPQuestions = new HashSet<CDPQuestions>();
        }
    
        public System.Guid Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<CDPQuestions> CDPQuestions { get; set; }
    }
}
