//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDPQuestionTables
    {
        public CDPQuestionTables()
        {
            this.CDPTableColumns = new HashSet<CDPTableColumns>();
            this.CDPTableRows = new HashSet<CDPTableRows>();
        }
    
        public System.Guid Id { get; set; }
        public string TableName { get; set; }
        public System.Guid Questionid { get; set; }
    
        public virtual CDPQuestions CDPQuestions { get; set; }
        public virtual ICollection<CDPTableColumns> CDPTableColumns { get; set; }
        public virtual ICollection<CDPTableRows> CDPTableRows { get; set; }
    }
}
