//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDPQuestionGroups
    {
        public System.Guid QGroupId { get; set; }
        public string QuestionGroupId { get; set; }
        public string QuestionGroupText { get; set; }
        public int Order { get; set; }
        public System.Guid QuestionnaireId { get; set; }
    
        public virtual CDPQuestionnaires CDPQuestionnaires { get; set; }
    }
}
