//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDPTabularQuestionAnswers
    {
        public System.Guid Id { get; set; }
        public System.Guid QuestionId { get; set; }
        public System.Guid PlantId { get; set; }
        public int Year { get; set; }
        public string GridColumn1 { get; set; }
        public string GridColumn2 { get; set; }
        public string GridColumn3 { get; set; }
        public string GridColumn4 { get; set; }
        public string GridColumn5 { get; set; }
        public string GridColumn6 { get; set; }
        public string GridColumn7 { get; set; }
        public string GridColumn8 { get; set; }
        public string GridColumn9 { get; set; }
        public string GridColumn10 { get; set; }
    }
}
