//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDPTableRows
    {
        public CDPTableRows()
        {
            this.CDPTableCells = new HashSet<CDPTableCells>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TableId { get; set; }
        public System.Guid PlantId { get; set; }
        public int Year { get; set; }
    
        public virtual CDPQuestionTables CDPQuestionTables { get; set; }
        public virtual ICollection<CDPTableCells> CDPTableCells { get; set; }
    }
}
