//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDPTableCells
    {
        public System.Guid Id { get; set; }
        public System.Guid RowId { get; set; }
        public System.Guid ColumnId { get; set; }
        public string Value { get; set; }
    
        public virtual CDPTableColumns CDPTableColumns { get; set; }
        public virtual CDPTableRows CDPTableRows { get; set; }
    }
}
