//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDPValidationTypes
    {
        public CDPValidationTypes()
        {
            this.CDPQuestionValidations = new HashSet<CDPQuestionValidations>();
        }
    
        public System.Guid Id { get; set; }
        public string ValidationType { get; set; }
    
        public virtual ICollection<CDPQuestionValidations> CDPQuestionValidations { get; set; }
    }
}
