//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMR_KMS_DB_DevEntities : DbContext
    {
        public SMR_KMS_DB_DevEntities()
            : base("name=SMR_KMS_DB_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application> Application { get; set; }
        public DbSet<ApplicationLog> ApplicationLog { get; set; }
        public DbSet<CDPDateRangeAnswers> CDPDateRangeAnswers { get; set; }
        public DbSet<CDPQuestionGroups> CDPQuestionGroups { get; set; }
        public DbSet<CDPQuestionnaires> CDPQuestionnaires { get; set; }
        public DbSet<CDPQuestionOptions> CDPQuestionOptions { get; set; }
        public DbSet<CDPQuestions> CDPQuestions { get; set; }
        public DbSet<CDPQuestionSubGroups> CDPQuestionSubGroups { get; set; }
        public DbSet<CDPQuestionTables> CDPQuestionTables { get; set; }
        public DbSet<CDPQuestionType> CDPQuestionType { get; set; }
        public DbSet<CDPQuestionValidations> CDPQuestionValidations { get; set; }
        public DbSet<CDPSimpleChoiceAnswers> CDPSimpleChoiceAnswers { get; set; }
        public DbSet<CDPTableCells> CDPTableCells { get; set; }
        public DbSet<CDPTableColumns> CDPTableColumns { get; set; }
        public DbSet<CDPTableInformations> CDPTableInformations { get; set; }
        public DbSet<CDPTableRows> CDPTableRows { get; set; }
        public DbSet<CDPTabularAnswer> CDPTabularAnswer { get; set; }
        public DbSet<CDPTabularQuestionAnswers> CDPTabularQuestionAnswers { get; set; }
        public DbSet<CDPValidationTypes> CDPValidationTypes { get; set; }
        public DbSet<EdmMetadata> EdmMetadata { get; set; }
        public DbSet<KMAdditionalInformations> KMAdditionalInformations { get; set; }
        public DbSet<KMAttributes> KMAttributes { get; set; }
        public DbSet<KMClosedDiscussion> KMClosedDiscussion { get; set; }
        public DbSet<KMComments> KMComments { get; set; }
        public DbSet<KMCorrectiveActions> KMCorrectiveActions { get; set; }
        public DbSet<KMCreditMaster> KMCreditMaster { get; set; }
        public DbSet<KMCustomer> KMCustomer { get; set; }
        public DbSet<KMDocuments> KMDocuments { get; set; }
        public DbSet<KMDocumentSubType> KMDocumentSubType { get; set; }
        public DbSet<KMDocumentType> KMDocumentType { get; set; }
        public DbSet<KMEmailNotification> KMEmailNotification { get; set; }
        public DbSet<KMFieldClaimClassification> KMFieldClaimClassification { get; set; }
        public DbSet<KMFollowingMessage> KMFollowingMessage { get; set; }
        public DbSet<KMFollowingUser> KMFollowingUser { get; set; }
        public DbSet<KMGroupMembers> KMGroupMembers { get; set; }
        public DbSet<KMGroups> KMGroups { get; set; }
        public DbSet<KMItems> KMItems { get; set; }
        public DbSet<KMLikeMessage> KMLikeMessage { get; set; }
        public DbSet<KMListAttributes> KMListAttributes { get; set; }
        public DbSet<KMMessage> KMMessage { get; set; }
        public DbSet<KMMessageTag> KMMessageTag { get; set; }
        public DbSet<KMMoMTeamMemberPresence> KMMoMTeamMemberPresence { get; set; }
        public DbSet<KMNotifications> KMNotifications { get; set; }
        public DbSet<KMPlant> KMPlant { get; set; }
        public DbSet<KMPlantExceptionList> KMPlantExceptionList { get; set; }
        public DbSet<KMPrivilege> KMPrivilege { get; set; }
        public DbSet<KMProblemCategory> KMProblemCategory { get; set; }
        public DbSet<KMProjectStepDocuments> KMProjectStepDocuments { get; set; }
        public DbSet<KMProjectStepMoM> KMProjectStepMoM { get; set; }
        public DbSet<KMQCProjectHistory> KMQCProjectHistory { get; set; }
        public DbSet<KMQCProjects> KMQCProjects { get; set; }
        public DbSet<KMQCProjectStepMapping> KMQCProjectStepMapping { get; set; }
        public DbSet<KMQCProjectSteps> KMQCProjectSteps { get; set; }
        public DbSet<KMQCTarget> KMQCTarget { get; set; }
        public DbSet<KMReports> KMReports { get; set; }
        public DbSet<KMReportTargetMapping> KMReportTargetMapping { get; set; }
        public DbSet<KMSubDocuments> KMSubDocuments { get; set; }
        public DbSet<KMTags> KMTags { get; set; }
        public DbSet<KMTeamMembers> KMTeamMembers { get; set; }
        public DbSet<KMTeams> KMTeams { get; set; }
        public DbSet<KMTraining> KMTraining { get; set; }
        public DbSet<KMUserCredits> KMUserCredits { get; set; }
        public DbSet<KMUserEmailNotification> KMUserEmailNotification { get; set; }
        public DbSet<KMWarranty> KMWarranty { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<RolesPrivilege> RolesPrivilege { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<CDPDateRangeAnswersHistory> CDPDateRangeAnswersHistory { get; set; }
        public DbSet<CDPSimpleChoiceAnswersHistory> CDPSimpleChoiceAnswersHistory { get; set; }
        public DbSet<CDPTabularAnswerHistory> CDPTabularAnswerHistory { get; set; }
        public DbSet<EmailNotificationLog> EmailNotificationLog { get; set; }
        public DbSet<KMGroups_Bak> KMGroups_Bak { get; set; }
        public DbSet<KMUserEmailNotification_20150910> KMUserEmailNotification_20150910 { get; set; }
        public DbSet<kmwarranty_1> kmwarranty_1 { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
