//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailNotificationLog
    {
        public string EmailTo { get; set; }
        public string EmailFrom { get; set; }
        public string TemplateName { get; set; }
        public System.DateTime SendingDate { get; set; }
        public bool IsSucess { get; set; }
        public string Remarks { get; set; }
    }
}
