//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMComments
    {
        public KMComments()
        {
            this.KMDocuments = new HashSet<KMDocuments>();
            this.KMFollowingMessage = new HashSet<KMFollowingMessage>();
            this.KMLikeMessage = new HashSet<KMLikeMessage>();
            this.KMQCProjects = new HashSet<KMQCProjects>();
        }
    
        public System.Guid CommentId { get; set; }
        public System.Guid RefId { get; set; }
        public string MessageComment { get; set; }
        public bool IsCommentActive { get; set; }
        public System.Guid PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual KMMessage KMMessage { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ICollection<KMDocuments> KMDocuments { get; set; }
        public virtual ICollection<KMFollowingMessage> KMFollowingMessage { get; set; }
        public virtual ICollection<KMLikeMessage> KMLikeMessage { get; set; }
        public virtual ICollection<KMQCProjects> KMQCProjects { get; set; }
    }
}
