//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMCustomer
    {
        public KMCustomer()
        {
            this.KMWarranty = new HashSet<KMWarranty>();
        }
    
        public System.Guid CustomerID { get; set; }
        public string CustomerName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<KMWarranty> KMWarranty { get; set; }
    }
}
