//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMDocumentType
    {
        public KMDocumentType()
        {
            this.KMDocuments = new HashSet<KMDocuments>();
            this.KMProjectStepDocuments = new HashSet<KMProjectStepDocuments>();
        }
    
        public System.Guid DocumentTypeId { get; set; }
        public string DocumentTypeName { get; set; }
    
        public virtual ICollection<KMDocuments> KMDocuments { get; set; }
        public virtual ICollection<KMProjectStepDocuments> KMProjectStepDocuments { get; set; }
    }
}
