//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMFieldClaimClassification
    {
        public System.Guid FieldClaimID { get; set; }
        public string FieldClaimName { get; set; }
        public bool IsActive { get; set; }
    }
}
