//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMGroups
    {
        public KMGroups()
        {
            this.KMGroupMembers = new HashSet<KMGroupMembers>();
            this.KMMessage = new HashSet<KMMessage>();
        }
    
        public System.Guid GroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public string GroupAvatarUrl { get; set; }
        public bool IsPublicGroup { get; set; }
        public bool IsGroupDeleted { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<bool> IsUserGroup { get; set; }
        public bool IsAllowedToEditMessage { get; set; }
        public bool IsAllowedToReorderMessage { get; set; }
    
        public virtual ICollection<KMGroupMembers> KMGroupMembers { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ICollection<KMMessage> KMMessage { get; set; }
    }
}
