//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMMessage
    {
        public KMMessage()
        {
            this.KMClosedDiscussion = new HashSet<KMClosedDiscussion>();
            this.KMComments = new HashSet<KMComments>();
            this.KMDocuments = new HashSet<KMDocuments>();
            this.KMFollowingMessage = new HashSet<KMFollowingMessage>();
            this.KMItems = new HashSet<KMItems>();
            this.KMLikeMessage = new HashSet<KMLikeMessage>();
            this.KMMessageTag = new HashSet<KMMessageTag>();
            this.KMQCProjects = new HashSet<KMQCProjects>();
            this.KMWarranty = new HashSet<KMWarranty>();
        }
    
        public System.Guid MessageId { get; set; }
        public System.Guid GroupId { get; set; }
        public System.Guid MessageTypeId { get; set; }
        public System.Guid ScopeId { get; set; }
        public string MessageTitle { get; set; }
        public string MessageContent { get; set; }
        public string MessageTags { get; set; }
        public bool IsMessageActive { get; set; }
        public Nullable<System.Guid> ClosedDiscussionId { get; set; }
        public bool IsKaizenCreated { get; set; }
        public System.Guid PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<decimal> KaizenId { get; set; }
    
        public virtual KMAttributes KMAttributes { get; set; }
        public virtual KMAttributes KMAttributes1 { get; set; }
        public virtual ICollection<KMClosedDiscussion> KMClosedDiscussion { get; set; }
        public virtual ICollection<KMComments> KMComments { get; set; }
        public virtual ICollection<KMDocuments> KMDocuments { get; set; }
        public virtual ICollection<KMFollowingMessage> KMFollowingMessage { get; set; }
        public virtual KMGroups KMGroups { get; set; }
        public virtual ICollection<KMItems> KMItems { get; set; }
        public virtual ICollection<KMLikeMessage> KMLikeMessage { get; set; }
        public virtual ICollection<KMMessageTag> KMMessageTag { get; set; }
        public virtual ICollection<KMQCProjects> KMQCProjects { get; set; }
        public virtual ICollection<KMWarranty> KMWarranty { get; set; }
    }
}
