//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMPlant
    {
        public KMPlant()
        {
            this.KMPlantExceptionList = new HashSet<KMPlantExceptionList>();
            this.KMQCProjects = new HashSet<KMQCProjects>();
            this.KMWarranty = new HashSet<KMWarranty>();
            this.Users = new HashSet<Users>();
        }
    
        public System.Guid PlantId { get; set; }
        public string PlantName { get; set; }
    
        public virtual ICollection<KMPlantExceptionList> KMPlantExceptionList { get; set; }
        public virtual ICollection<KMQCProjects> KMQCProjects { get; set; }
        public virtual ICollection<KMWarranty> KMWarranty { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
