//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMPrivilege
    {
        public KMPrivilege()
        {
            this.RolesPrivilege = new HashSet<RolesPrivilege>();
        }
    
        public System.Guid PrivilegeId { get; set; }
        public string PrivilegeController { get; set; }
        public string PrivilegeAction { get; set; }
    
        public virtual ICollection<RolesPrivilege> RolesPrivilege { get; set; }
    }
}
