//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMProjectStepMoM
    {
        public KMProjectStepMoM()
        {
            this.KMMoMTeamMemberPresence = new HashSet<KMMoMTeamMemberPresence>();
            this.KMProblemCategory = new HashSet<KMProblemCategory>();
        }
    
        public System.Guid MoMId { get; set; }
        public System.Guid StepMappingId { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public int MeetingNo { get; set; }
        public System.TimeSpan MeetingTime { get; set; }
        public string SpecialPresence { get; set; }
        public string MeetingContent { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<KMMoMTeamMemberPresence> KMMoMTeamMemberPresence { get; set; }
        public virtual ICollection<KMProblemCategory> KMProblemCategory { get; set; }
        public virtual KMQCProjectStepMapping KMQCProjectStepMapping { get; set; }
    }
}
