//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMProjectStepDocuments
    {
        public System.Guid StepDocumentId { get; set; }
        public System.Guid StepMappingId { get; set; }
        public System.Guid DocumentTypeId { get; set; }
        public string DocumentUrl { get; set; }
        public System.Guid PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual KMDocumentType KMDocumentType { get; set; }
        public virtual KMQCProjectStepMapping KMQCProjectStepMapping { get; set; }
    }
}
