//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMQCTarget
    {
        public System.Guid TargetId { get; set; }
        public System.Guid ReportIdentity { get; set; }
        public string ReportHeader { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<int> TargetValue { get; set; }
        public System.Guid UnitId { get; set; }
    }
}
