//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMQCProjectSteps
    {
        public System.Guid StepId { get; set; }
        public string StepName { get; set; }
        public string StepDescription { get; set; }
        public int StepOrder { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public string StepGuidelinesUrl { get; set; }
        public string StepSamplePresentationUrl { get; set; }
    }
}
