//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMQCProjectStepMapping
    {
        public KMQCProjectStepMapping()
        {
            this.KMProjectStepDocuments = new HashSet<KMProjectStepDocuments>();
            this.KMProjectStepMoM = new HashSet<KMProjectStepMoM>();
        }
    
        public System.Guid StepMappingId { get; set; }
        public System.Guid MessageId { get; set; }
        public System.Guid StepId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<KMProjectStepDocuments> KMProjectStepDocuments { get; set; }
        public virtual ICollection<KMProjectStepMoM> KMProjectStepMoM { get; set; }
    }
}
