//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMQCProjects
    {
        public System.Guid QCProjectId { get; set; }
        public System.Guid MessageId { get; set; }
        public System.Guid PlantId { get; set; }
        public System.Guid TeamId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> SubmitStatus { get; set; }
        public Nullable<System.Guid> CommentId { get; set; }
        public string FrequencyOfMeeting { get; set; }
        public string ProjectArea { get; set; }
        public string SpecifyProjectArea { get; set; }
    
        public virtual KMComments KMComments { get; set; }
        public virtual KMMessage KMMessage { get; set; }
        public virtual KMPlant KMPlant { get; set; }
        public virtual KMTeams KMTeams { get; set; }
    }
}
