//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMReports
    {
        public int ReportId { get; set; }
        public string ReportName { get; set; }
        public System.Guid ReportIdentity { get; set; }
        public Nullable<bool> CanSetTarget { get; set; }
        public Nullable<bool> VisibleStatus { get; set; }
        public Nullable<bool> CanExport { get; set; }
    }
}
