//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMReportTargetMapping
    {
        public System.Guid TargetTypeId { get; set; }
        public System.Guid ReportIdentity { get; set; }
        public string TargetType { get; set; }
        public string TargetName { get; set; }
    }
}
