//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMTeamMembers
    {
        public KMTeamMembers()
        {
            this.KMMoMTeamMemberPresence = new HashSet<KMMoMTeamMemberPresence>();
        }
    
        public System.Guid TeamMemberId { get; set; }
        public System.Guid TeamId { get; set; }
        public string MemberName { get; set; }
        public string MemberEmail { get; set; }
        public string MemberType { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ImageDataURL { get; set; }
        public string EmpCode { get; set; }
        public string Gender { get; set; }
        public string Qualification { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public Nullable<bool> ISActiveMember { get; set; }
    
        public virtual ICollection<KMMoMTeamMemberPresence> KMMoMTeamMemberPresence { get; set; }
        public virtual KMTeams KMTeams { get; set; }
    }
}
