//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMTraining
    {
        public System.Guid TrainingId { get; set; }
        public System.Guid PlantId { get; set; }
        public string ModuleName { get; set; }
        public string SubModuleName { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public int ParticipantNumber { get; set; }
        public decimal TrainingDuration { get; set; }
        public Nullable<decimal> ManHrs { get; set; }
        public string TrainerName { get; set; }
        public string TrainingType { get; set; }
        public string TrainingLocation { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
