//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.RolesPrivilege = new HashSet<RolesPrivilege>();
            this.Users = new HashSet<Users>();
        }
    
        public System.Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public bool IsMemberShipRequired { get; set; }
        public bool IsQCApprover { get; set; }
        public Nullable<bool> CanEditTarget { get; set; }
    
        public virtual ICollection<RolesPrivilege> RolesPrivilege { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
