//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdlcRDLCReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesPrivilege
    {
        public System.Guid RolePrivilegeId { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid PrivilegeId { get; set; }
    
        public virtual KMPrivilege KMPrivilege { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
